project:
  type: book
  output-dir: docs

book:
  title: "Introduction to NFL Analytics with R"
  reader-mode: true
  author:
    name: Bradley J. Congelio
    orcid: 0009-0000-0652-4145
  site-url: https://bradcongelio.com/nfl-analytics-with-r-book
  repo-url: https://github.com/bcongelio/nfl-analytics-with-r-book
  repo-branch: origin
  sharing: [twitter, facebook, linkedin]
  publisher: "CRC Press"
  publisher-place: "Boca Raton, FL."
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - 01-nfl-analytics-and-r.qmd
    - 02-nfl-analytics-tidyverse.qmd
    - 03-nfl-analytics-functions.qmd
    - 04-nfl-analytics-visualization.qmd
    - 05-nfl-analytics-advanced-methods.qmd
  appendices:
    - a1-nfl-analytics-dictionary.qmd
    - a2-nfl-further-reading.qmd

search: true

page-footer: 
  left: |
    NFL Analytics with R was written by Bradley J. Congelio.
  right: |
    This book was built with <a href = "https://quarto.org/">Quarto</a>
bibliography: citations.bib


format:
  html:
    theme:
      - cosmo
      - nfl-analytics.scss
    code-link: true
    code-overflow: wrap
    fig-align: center
    fig-cap-location: bottom
    author-meta: "Bradley Congelio"
    

  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    fig-align: center
    fig-cap-location: bottom
